"""empty message

Revision ID: a586c628080f
Revises: 
Create Date: 2021-07-27 21:01:20.981674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a586c628080f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_image', sa.String(length=500), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following'], ['users.id'], )
    )
    op.create_table('bystanders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comment_thread',
    sa.Column('post', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['reply'], ['comments.id'], )
    )
    op.create_table('fighters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('fighter_height', sa.Integer(), nullable=False),
    sa.Column('fighter_weight', sa.Integer(), nullable=False),
    sa.Column('fighter_reach', sa.Integer(), nullable=True),
    sa.Column('fighting_style', sa.String(length=500), nullable=True),
    sa.Column('fighter_age', sa.Integer(), nullable=True),
    sa.Column('fighter_wins', sa.Integer(), nullable=False),
    sa.Column('fighter_losses', sa.Integer(), nullable=False),
    sa.Column('fighter_titles', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('promoters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promoters')
    op.drop_table('fighters')
    op.drop_table('comment_thread')
    op.drop_table('bystanders')
    op.drop_table('follows')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('user_types')
    # ### end Alembic commands ###
